### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by MichalPB1** [arif-rh/ci4-dynamic-model#1]
Hi,
Are you planning to add other relationships, i.e.
- Many To Many
- Has One Through
- Has Many Through

**Comment by arif-rh** [comment]
Hi @MichalPB1 

Yes, I am planning to add other relationships, as you mention, but maybe not in short time.  Because right now, my work take much of my times.

**Comment by mrelliot69** [comment]
any updates on this @arif-rh ?

**Comment by arif-rh** [comment]
I am refactoring this library and make some big changes, so probably the new feature will be on next major version. But it will not be release soon, since still on my own alpha test.
