### ISSUE TITLE
Incompatible codeigniter 4.1.2

### ISSUE THREAD

**Issue by zoom360** [arif-rh/ci4-dynamic-model#2]

**Comment by arif-rh** [comment]
Hi @zoom360 

You may can see inside composer.json file, that this package in require-dev still point to codeigniter 4.0, so yes, this packages is still not tested yet on codeigniter 4.1.2

But if you have some fixes or adjustment to work in latest codeigniter, you can submit pull request with the testing unit too.

Thanks.
